"""init

Revision ID: 9a45f6c18248
Revises:
Create Date: 2026-02-03 18:22:36.735605

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9a45f6c18248"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("region", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=True),
        sa.Column("admin_port", sa.Integer(), nullable=True),
        sa.Column(
            "capabilities", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agents_region"), "agents", ["region"], unique=False)
    op.create_table(
        "pipelines",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("spec", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "assignments",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("agent_id", sa.String(length=64), nullable=False),
        sa.Column("region", sa.String(length=64), nullable=False),
        sa.Column("pipeline_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["pipeline_id"], ["pipelines.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assignments_agent_id"), "assignments", ["agent_id"], unique=False
    )
    op.create_index(
        "ix_assignments_agent_region",
        "assignments",
        ["agent_id", "region"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assignments_pipeline_id"), "assignments", ["pipeline_id"], unique=False
    )
    op.create_index(
        op.f("ix_assignments_region"), "assignments", ["region"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_assignments_region"), table_name="assignments")
    op.drop_index(op.f("ix_assignments_pipeline_id"), table_name="assignments")
    op.drop_index("ix_assignments_agent_region", table_name="assignments")
    op.drop_index(op.f("ix_assignments_agent_id"), table_name="assignments")
    op.drop_table("assignments")
    op.drop_table("pipelines")
    op.drop_index(op.f("ix_agents_region"), table_name="agents")
    op.drop_table("agents")
    # ### end Alembic commands ###
